[package]
name = "wasm_thread"
version = "0.1.0"
authors = ["chemicstry <chemicstry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "Window", "Blob", "Url", "WorkerOptions"]}
js-sys = "0.3"

[dev-dependencies]
log = "0.4"
env_logger = "0.7"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
console_log = { version = "0.2", features = ["color"] }
console_error_panic_hook = "0.1"
